export const CREATED_RESPONSE_CODE = 201;
export const SUCCESS_RESPONSE_CODE = 200;
export const NOT_FOUND_RESPONSE_CODE = 404;
export const UNAUTHORIZED_RESPONSE_CODE = 401;
export const FORBIDDEN_RESPONSE_CODE = 403;
export const SERVER_ERROR_RESPONSE_CODE = 500;
